services:
  goginapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goginapp
    ports:
      - "8080:8080"
    links:
      - gogin-postgres
    depends_on:
      - gogin-postgres
    environment:
      - POSTGRES_HOST=gogin-postgres
      - POSTGRES_DB=gogin
      - POSTGRES_USER=gogin
      - POSTGRES_PASSWORD=secretpass
    volumes:
      - .:/go/src/app/
  gogin-postgres:
    image: postgres
    container_name: gogin-postgres
    environment:
      - POSTGRES_DB=gogin
      - POSTGRES_USER=gogin
      - POSTGRES_PASSWORD=secretpass
    ports:
      - 5432:5432
    volumes:
      - goginapp-postgres-data:/var/lib/postgresql/data
volumes:
  goginapp-postgres-data:
    driver: local
